#!/usr/bin/env python3
import os

os.environ['UNRAR_LIB_PATH'] = os.path.dirname(os.path.realpath(__file__)) + '/libunrar/libunrar.so'

from comicstreamerlib.main import main

if __name__ == '__main__':
    main()
