#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -*- mode: Python; tab-width: 4; indent-tabs-mode: nil; -*-
# Do not change the previous lines. See PEP 8, PEP 263.

import os

os.environ['UNRAR_LIB_PATH'] = os.path.dirname(
    os.path.realpath(__file__)) + '/libunrar/libunrar.so'

from comicstreamerlib.main import main

if __name__ == '__main__':
    main()
